spring:
  application:
    name: tool-kit
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    org:
      springframework:
        web: DEBUG
server:
  port: 7077
